version: '3.3'

services:
    sendsay-integration:
        container_name: sendsay-integration
        build:
            context: .
            dockerfile: Dockerfile-prod
        command: dist/index.js
        restart: always
        ports:
            - "${PORT}:${PORT}"
        expose:
            - ${PORT}
        env_file:
            - ./.env
